title: Mercury's Blog
email: hi@nikhilbastola.com.np
description: Mercury's Blog 
baseurl: "/m3" 
url: "https://zmercury.github.io" 
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed
exclude:
  - minima.scss
